source "https://rubygems.org"

gem "asciidoctor"
gem "rake"

gem "json"
gem "awesome_print"

gem "asciidoctor-epub3"
gem "asciidoctor-pdf"

gem "coderay"
gem "pygments.rb"
gem "thread_safe"
gem "kindlegen"
