namespace :sstic do
  desc 'prepare build'
  task :prebuild do
    Dir.mkdir 'images' unless Dir.exists? 'images'
    Dir.glob("../stage-*/**/rk_*.[jpg][ipn][gf]").each do |image|
      FileUtils.copy(image, "images/" + File.basename(image))
    end
  end

  desc 'build basic formats'
  task :build => :prebuild do
    puts "Converting to HTML ..."
    `bundle exec asciidoctor main.asc`
    puts " -- HTML output at main.html"

    #puts "Converting to EPub..."
    #`bundle exec asciidoctor-epub3 main.asc`
    #puts " -- Epub output at main.epub"

    puts "Converting to PDF ..."
    `bundle exec asciidoctor-pdf main.asc`
    puts " --PDF output at main.pdf"
  end
end

task :default => "sstic:build"
